### ISSUE TITLE
ModuleNotFoundError: No module named 'colmap_wrapper'

### ISSUE THREAD

**Issue by Baptiste-AIST** [meyerls/aruco-estimator#15]
Hello, great work on this module, it seems working well!

I had an issue with the module 'colmap_wrapper', I think you forgot to include it in the submodules. 
I found in the history that you use this project as a submodule [colmap_wrapper](https://github.com/meyerls/colmap-wrapper), after cloning and installing it it worked fine. 

For anyone having the issue clone the wrapper repository and install it using pip install . in your environment

**Comment by meyerls** [comment]
Thanks! Yes it seemed as I did forget to include the [colmap_wrapper](https://pypi.org/project/colmap-wrapper/) module which is also available as a package. Nevertheless, your solution works for those who encounter similar errors.
