### ISSUE TITLE
[DISCUSSION] Possibility to re generate scaled text export

### ISSUE THREAD

**Issue by Baptiste-AIST** [meyerls/aruco-estimator#22]
Hi, I would like to know if it could be possible to add an option to generate a new set of values like export as text option in COLMAP.

It generates 3 files: - cameras.txt, images.txt and points3D.txt
Those files are needed when using Nerf Instant-NGP to generate the transforms.json

Thank you

**Comment by meyerls** [comment]
Hi,

I'm sorry for not getting back to you sooner. I added the feature to save the scaled parameters as .txt by default. Please check if it works for you. Thanks!
